-- MySQL Script generated by MySQL Workbench
-- qua 02 abr 2025 09:56:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cozinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cozinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cozinha` ;
USE `cozinha` ;

-- -----------------------------------------------------
-- Table `cozinha`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(120) NULL,
  `email` VARCHAR(80) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nome_perfil` VARCHAR(20) NOT NULL,
  `favoritos` VARCHAR(100) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC) VISIBLE,
  UNIQUE INDEX `nome_perfil_UNIQUE` (`nome_perfil` ASC) VISIBLE,
  INDEX `fk_perfil_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cozinha`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`receita` (
  `idreceita` INT NOT NULL AUTO_INCREMENT,
  `nome_comida` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ingredientes` VARCHAR(45) NOT NULL,
  `modo_de_preparo` VARCHAR(500) NOT NULL,
  `tempo` VARCHAR(20) NOT NULL,
  `rendimento` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `regiao` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idreceita`),
  UNIQUE INDEX `idReceitas_UNIQUE` (`idreceita` ASC) VISIBLE,
  INDEX `fk_receita_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_receita_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cozinha`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`receita_has_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`receita_has_perfil` (
  `receita_idreceita` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`receita_idreceita`, `perfil_idperfil`),
  INDEX `fk_receita_has_perfil_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  INDEX `fk_receita_has_perfil_receita1_idx` (`receita_idreceita` ASC) VISIBLE,
  CONSTRAINT `fk_receita_has_perfil_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `cozinha`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_perfil_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `cozinha`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `nota` VARCHAR(45) NULL,
  `receita_has_perfil_receita_idreceita` INT NOT NULL,
  `receita_has_perfil_perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  UNIQUE INDEX `idavaliacao_UNIQUE` (`idavaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_receita_has_perfil1_idx` (`receita_has_perfil_receita_idreceita` ASC, `receita_has_perfil_perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_receita_has_perfil1`
    FOREIGN KEY (`receita_has_perfil_receita_idreceita` , `receita_has_perfil_perfil_idperfil`)
    REFERENCES `cozinha`.`receita_has_perfil` (`receita_idreceita` , `perfil_idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
