-- MySQL Script generated by MySQL Workbench
-- qui 24 abr 2025 09:38:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cozinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cozinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cozinha` ;
USE `cozinha` ;

-- -----------------------------------------------------
-- Table `cozinha`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nome_perfil` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC) VISIBLE,
  UNIQUE INDEX `nome_perfil_UNIQUE` (`nome_perfil` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`receita` (
  `idreceita` INT NOT NULL AUTO_INCREMENT,
  `nome_comida` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ingredientes` VARCHAR(100) NOT NULL,
  `modo_de_preparo` VARCHAR(1000) NOT NULL,
  `tempo` VARCHAR(20) NOT NULL,
  `rendimento` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `regiao` VARCHAR(45) NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idreceita`),
  UNIQUE INDEX `idReceitas_UNIQUE` (`idreceita` ASC) VISIBLE,
  INDEX `fk_receita_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_receita_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `cozinha`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`favoritos` (
  `perfil_idperfil` INT NOT NULL,
  `receita_idreceita` INT NOT NULL,
  PRIMARY KEY (`perfil_idperfil`, `receita_idreceita`),
  INDEX `fk_perfil_has_receita_receita1_idx` (`receita_idreceita` ASC) VISIBLE,
  INDEX `fk_perfil_has_receita_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_has_receita_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `cozinha`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_has_receita_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `cozinha`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cozinha`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cozinha`.`avaliacao` (
  `perfil_idperfil` INT NOT NULL,
  `receita_idreceita` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `nota` DECIMAL(2,1) NULL,
  PRIMARY KEY (`perfil_idperfil`, `receita_idreceita`),
  INDEX `fk_perfil_has_receita_receita2_idx` (`receita_idreceita` ASC) VISIBLE,
  INDEX `fk_perfil_has_receita_perfil2_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_has_receita_perfil2`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `cozinha`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_has_receita_receita2`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `cozinha`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE cozinha;
INSERT INTO perfil (nome, nome_perfil, senha, email) VALUES
('João da Silva', 'joaosilva', 'senha123', 'joao@email.com'),
('Maria Oliveira', 'mariaoliveira', 'senha456', 'maria@email.com'),
('Carlos Souza', 'carlossouza', 'senha789', 'carlos@email.com'),
('Ana Pereira', 'anapereira', 'senhaabc', 'ana@email.com'),
('Lucas Lima', 'lucaslima', 'senhalucas', 'lucas@email.com');

INSERT INTO receita (
    nome_comida, tipo, ingredientes, modo_de_preparo,
    tempo, rendimento, foto, regiao, perfil_idperfil
) VALUES
('Bolo de Cenoura', 'Doce', 'cenoura, farinha, ovos, açúcar', 'Misture tudo e asse por 40 minutos.', '40 minutos', '8 porções', 'bolo.jpg', 'Sudeste', 1),
('Feijoada', 'Prato Principal', 'feijão preto, carne seca, linguiça', 'Cozinhe os ingredientes por 2 horas.', '2 horas', '6 porções', 'feijoada.jpg', 'Centro-Oeste', 2),
('Moqueca', 'Peixe', 'peixe, cebola, pimentão, leite de coco', 'Cozinhe os ingredientes no leite de coco.', '45 minutos', '4 porções', 'moqueca.jpg', 'Nordeste', 3),
('Pudim de Leite', 'Sobremesa', 'leite condensado, ovos, leite', 'Asse em banho-maria por 1 hora.', '1 hora', '10 porções', 'pudim.jpg', 'Sudeste', 4),
('Arroz Carreteiro', 'Prato Principal', 'arroz, carne seca, cebola', 'Frite os ingredientes e adicione arroz cozido.', '30 minutos', '5 porções', 'carreteiro.jpg', 'Sul', 5);

INSERT INTO favoritos (perfil_idperfil, receita_idreceita) VALUES
(1, 2),
(2, 1),
(3, 4),
(4, 3),
(5, 5);

INSERT INTO avaliacao (perfil_idperfil, receita_idreceita, comentario, nota) VALUES
(1, 2, 'Muito saborosa!', 5.0),
(2, 1, 'Delicioso bolo!', 4.5),
(3, 4, 'Gostei do pudim!', 4.0),
(4, 3, 'Excelente moqueca!', 4.8),
(5, 5, 'Muito bom e rápido de fazer.', 4.3);

